[package]
name = "optd-datafusion-repr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arrow-schema = "47.0.0"
num-traits = "0.2"
num-derive = "0.2"
tracing = "0.1"
ordered-float = "4"
tracing-subscriber = "0.3"
pretty-xmlish = "0.1"
itertools = "0.11"
optd-core = { path = "../optd-core" }
optd-gungnir = { path = "../optd-gungnir" }
camelpaste = "0.1"
datafusion-expr = "32.0.0"
async-trait = "0.1"
datafusion = "32.0.0"
assert_approx_eq = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = {version = "3.7.0", features = ["json"]}
bincode = "1.3.3"
rayon = "1.10"
union-find = { git = "https://github.com/Gun9niR/union-find-rs.git", rev = "794821514f7daefcbb8d5f38ef04e62fc18b5665" }
test-case = "3.3"
chrono = "0.4"
